version: '3'
services:
  postgres:
    build:
      context: null
      dockerfile: dockerfile
    container_name: postgres
    restart: always
    enviroment:
      POSTGRES_PASSWORD: "root"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5443:5443
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      postgres_network:
        aliases:
          - postgres_host
  volumes:
    pgdata: {}
  networks:
    postgres_network:
      name: postgres_net
      drive: bridge
