version: '2.3'
services:
  web_1:
    container_name: system_control
    build: .
    ports:
      - 4500:80
      - 443:443
    volumes:
      - ./Projects/web1:/var/www
      - ./Virtualhost/web1:/etc/apache2/sites-available
     # - ./SSL:/etc/ssl/certs
    depends_on: 
      - web_2
      - database

  web_2:
    container_name: system_control2
    image: php:5.6.14-apache
    ports:
      - 4501:80
    volumes:
      - ./Projects/web2:/var/www
      - ./Virtualhost/web2:/etc/apache2/sites-available
     # - ./SSL:/etc/ssl/certs

  database:
    image: postgres:9.4
    restart: always
    ports:
      - 5432:5432
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
